### ISSUE TITLE
Configure MQTT broker

### ISSUE THREAD

**Issue by pylapp** [snipsco/snips-platform-android-demo#4]
Hi!
How can we configure the IP address and the port of the MQTT broker?
I would like to have this Android prototype publish actions in a dedicated broker I have subscribed on in another computer.
How can we do that?

**Comment by pylapp** [comment]
I had the answer thanks to this Twitter thread: https://twitter.com/pylapp/status/958015558288662529

Thank you guys!

**Comment by thanksmister** [comment]
This Twitter thread no longer exists. Is it possible to list the solution here so that others might find it?

**Comment by pylapp** [comment]
Hi!

I thought there was an MQQT broker implemented in the Android client, I was looking looking for it. But that thread taught me at that time the broker was not implemented. So did I choose to not use MQQT in my project :)

Cheers

**Comment by fredszaq** [comment]
@thanksmister the android SDK doesn't support MQTT bridging for now. If you want to connect to an MQTT install you need touse an MQTT client (paho-mqtt is a good example)

Here are the relevant parts of the documentation regarding the hermes protocol used on mqtt https://snips.gitbook.io/documentation/ressources/multi-turn-dialog and https://snips.gitbook.io/documentation/ressources/hermes-protocol

**Comment by thanksmister** [comment]
Yes that makes now.  I can just implement MQTT in Android to forward the  Snips intent information (from the SDK callbacks) to HASS or any MQTT broker.   Thanks for the information.
