### ISSUE TITLE
Querying without voice

### ISSUE THREAD

**Issue by KasparPeterson** [snipsco/snips-platform-android-demo#9]
Thank you for this neat platform and helpful demo. 
I am wondering if it is possible to query the platform without using voice? 
In otherwords, matching text input to intent.

I am aware of dialogflow and rasa and other similar solutions but I would really like to solve everything offline.

**Comment by startupgurukul** [comment]
You came to wrong place checkout dialogflow.com from Google

**Comment by KasparPeterson** [comment]
@startupgurukul Edited my comment.

**Comment by KasparPeterson** [comment]
Thanks a lot for your time. Probably looking in that direction.
